<?php print '<?php' ?>
/**
 * Database Model for "<?php $tpl->table_name ?>"
 * 
 * This file has been automatically generated by the Nutshell
 * Model Generator Plugin.
 * 
 * @since <?php print date('d/m/Y'); ?>
 */
namespace application\model<?php $tpl->folder ?>
{
	use nutshell\plugin\mvc\model\CRUD;
	
	<?php $tpl->table_comment ?>class <?php $tpl->model_name ?> extends CRUD
	{
		public $name		= '<?php $tpl->table_name ?>';
		public $primary		= <?php $tpl->pk_array_str ?>;
		public $primary_ai	= <?php $tpl->primary_ai_str ?>;
		public $autoCreate	= <?php $tpl->autoCreate_str ?>;
		
		public $columns    = <?php $tpl->column_definition ?>;
	}
}
<?php print '?>' ?>